// <auto-generated />
using AgileCourseAssignment.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgileCourseAssignment.Server.Migrations
{
    [DbContext(typeof(FlagScapeDb))]
    [Migration("20230919073549_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgileCourseAssignment.Shared.Models.FlagsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Germany",
                            Description = "The tricolour flag was designed in 1832, and the black, red, and gold colours were taken from the uniforms of German soldiers during the Napoleonic Wars.",
                            Image = "Germany.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Austria",
                            Description = "Stripes of red and white have been a collective emblem of Austria for over 800 years, and they were first used on the flag in 1191.",
                            Image = "Austria.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Spain",
                            Description = "The flag of Spain was officially adopted on 19 July 1927 as the merchant naval flag, and on 29 December 1978 as the national flag in order to easily differentiate his ships from those of other European nations. ",
                            Image = "spain.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Belgium",
                            Description = "Black, gold and red are symbolic of the country's coat of arms. The three-striped vertical layout was inspired by the French Tricolour. Black and gold were chosen where the Belgian Revolution started and red was added as a symbol of the blood spilled during the uprising.",
                            Image = "Belgium.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "Bulgaria",
                            Description = "The flag of Bulgaria was adopted in 1989 and consists of three horizontal bands of white, green and red.",
                            Image = "Bulgaria.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "Croatia",
                            Description = "The flag of Croatia, adopted in December 1990, consists of three equal horizontal stripes of red, white and blue and the coat of arms of Croatia in the center.",
                            Image = "Croatia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Denmark",
                            Description = "It is the world's oldest state flag still in use. Legend has it that it appeared as a sign from heaven to King Valdemar II in 1219. This blood-red flag with an off-centred white cross became a model for other regional flags.",
                            Image = "Denmark.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Estonia",
                            Description = "It was officially re-adopted on May 8, 1990.Blue represents loyalty, and the country's beautiful blue skies, seas and lakes; black is symbolic of past oppression and the fertile soil; and white represents virtue, winter snows",
                            Image = "Estonia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Finland",
                            Description = "The off-centred blue cross is based on the Nordic Cross, widely used on Nordic national flags. The blue colour is symbolic of blue skies, and the thousands of lakes in Finland. The white represents the winter snows.",
                            Image = "Finland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Iceland",
                            Description = "The flag of Iceland was adopted in June 1915 to represent Iceland. It is a reverse colour image of the Flag of Norway. The blue represents the sea, the white represents the snow and glaciers and the red symbolises volcanic lava.",
                            Image = "Iceland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Italy",
                            Description = "Derived from an original design by Napoleon, it consists of three vertical bands of equal width, displaying the national colours of Italy: green, white, and red. Green stands for hope, white for loyalty and red represents the blood spread to unify the country.",
                            Image = "Italy.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Lithuania",
                            Description = "Yellow is symbolic of the country's wheat fields, green symbolic of the forests, and red symbolises patriotism. Collectively the colours represent hope for the future, freedom from oppression, and the courage",
                            Image = "Lithuania.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Poland",
                            Description = "The flag of Poland was officially adopted on August 1, 1919. The colours red and white have long been associated with Poland and its coat of arms, at least since 3 May 1791.",
                            Image = "Poland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "Slovakia",
                            Description = "Adopted on September 1, 1992. White, blue and red are traditional Pan-Slavic colours. The superimposed Slovakian arms feature a dominant white cross atop a blue symbolic reference to the European country's mountains.",
                            Image = "Slovakia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Slovenia",
                            Description = "Adopted on June 24, 1991. Red, white, and blue are taken from the Carniolan coat of arms. The mountains shown in white are representative of the Alps, and Mount Triglav, Slovenia's national symbol, in particular",
                            Image = "Slovenia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Sweden",
                            Description = "Was officially adopted on June 22, 1906. The off-centre yellow cross (the Nordic Cross) is taken from the Danish flag. The yellow and blue colours are taken from the national coat of arms.",
                            Image = "Sweden.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Turkey",
                            Description = "The flag of Turkey is a red flag with a white crescent moon and a star in its centre. The flag is called Ay Yıldız ( Moon Star) or Red flag. It was adopted in 1844 with the Tanzimat reforms; though the shape, placement and shade of the colour .",
                            Image = "Turkey.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "Albania",
                            Description = "The flag of Albania, adopted in April 1912, is a red flag with a black two-headed eagle in the centre. It is derived from the seal of Gjergj Skanderbeg, on 15th-century  who led a revolt against the Ottoman Empire that resulted in brief independence for Albania from 1443 ",
                            Image = "Albania.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Czech Republic",
                            Description = "The first flag of Czechoslovakia was white over red, and those colours are the heraldic colours of Bohemia. The blue triangle was added to the flag to distinguish it from the flag of Poland, and blue is said to represent the State of Moravia.",
                            Image = "Czech.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Hungary",
                            Description = "The flag of Hungary was officially adopted in 1848.\r\nThe colors of the tricolour design are derived from the historical Hungarian coat of arms. Red is said to symbolise strength, white faithfulness, and green hope.",
                            Image = "Hungary.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Ireland",
                            Description = "Dating from the 19th century and officially adopted in 1937. the colours of the Irish tricolour symbolise two communities. Green represents the Roman Catholic nationalist tradition. Orange represents the Protestant unionist community.",
                            Image = "Ireland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Latvia",
                            Description = "The flag of Latvia was officially re-adopted on February 27, 1990.The design is adopted from a 13th-century chronicle where \"red divided by white\" is said to be a Latvian flag.",
                            Image = "Latvia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Norway",
                            Description = "The flag of Norway is red with a blue Nordic cross outlined in white; the vertical part of the cross is shifted to the hoist side in the style of the Dannebrog, the flag of Denmark. It was adopted in 1821.",
                            Image = "Norway.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Ukraine",
                            Description = "Was adopted in 1991, shortly after the collapse of the former Soviet Union. The shade of blue is said to be symbolic of the sky, while the yellow represents Ukraine's golden wheat fields.",
                            Image = "Ukraine.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "France",
                            Description = "Officially adopted on February 15, 1794. Red, white and blue have come to represent liberty, equality and fraternity—the ideals of the French Revolution. ",
                            Image = "France.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Greece",
                            Description = "Adopted as the national flag in 1978. The alternating white and blue stripes are said to represent the nine syllables of the phrase \"Eleftheria i thanatos\" (\"Freedom or Death\"), a popular motto during the Greek War of Independence.",
                            Image = "Greece.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Portugal",
                            Description = "Adopted in 1911. The colours representing the hope of the nation (green) and the blood (red) of those who died defending it.",
                            Image = "Portugal.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Netherlands",
                            Description = "The flag of Luxembourg was officially adopted in 1972 and uses a combination of red, white, and blue that dates to the 13th century",
                            Image = "Netherlands.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Switzerland",
                            Description = "The flag of Switzerland consists of a red square with a bold, equilateral white Greek cross in the centre. It is one of only two square flags, the other being that of the Vatican City.",
                            Image = "Switzerland.png",
                            IsUsed = false
                        });
                });

            modelBuilder.Entity("AgileCourseAssignment.Shared.Models.HighScoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HighScore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player1",
                            Score = 250,
                            Time = 120
                        },
                        new
                        {
                            Id = 2,
                            Name = "Player2",
                            Score = 180,
                            Time = 90
                        },
                        new
                        {
                            Id = 3,
                            Name = "Player3",
                            Score = 320,
                            Time = 150
                        },
                        new
                        {
                            Id = 4,
                            Name = "Player4",
                            Score = 200,
                            Time = 110
                        },
                        new
                        {
                            Id = 5,
                            Name = "Player5",
                            Score = 280,
                            Time = 130
                        });
                });

            modelBuilder.Entity("AgileCourseAssignment.Shared.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyInformation = "Im glad to announce that a project has started for fun learning experience.",
                            Titel = "Development"
                        },
                        new
                        {
                            Id = 2,
                            BodyInformation = "There is now a Quiz game where you guess the flag!",
                            Titel = "Quiz v.1"
                        },
                        new
                        {
                            Id = 3,
                            BodyInformation = "There is now a highscore page where you can compare results from yourself and others.",
                            Titel = "Highscore table"
                        },
                        new
                        {
                            Id = 4,
                            BodyInformation = "A second Quiz game has been added, check it out!",
                            Titel = "Quiz v.2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
