// <auto-generated />
using AgileCourseAssignment.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgileCourseAssignment.Server.Migrations
{
    [DbContext(typeof(FlagScapeDb))]
    [Migration("20230907131756_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgileCourseAssignment.Shared.Models.FlagsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Flags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Germany",
                            Image = "Germany.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Austria",
                            Image = "Austria.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Spain",
                            Image = "spain.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Belgium",
                            Image = "Belgium.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "Bulgaria",
                            Image = "Bulgaria.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "Croatia",
                            Image = "Croatia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Denmark",
                            Image = "Denmark.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Estonia",
                            Image = "Estonia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Finland",
                            Image = "Finland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Iceland",
                            Image = "Iceland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Italy",
                            Image = "Italy.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Lithuania",
                            Image = "Lithuania.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Poland",
                            Image = "Poland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "Slovakia",
                            Image = "Slovakia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Slovenia",
                            Image = "Slovenia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Sweden",
                            Image = "Sweden.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Turkey",
                            Image = "Turkey.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "Albania",
                            Image = "Albania.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Czech Republic",
                            Image = "Czech.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Hungary",
                            Image = "Hungary.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Ireland",
                            Image = "Ireland.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Latvia",
                            Image = "Latvia.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Norway",
                            Image = "Norway.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Ukraine",
                            Image = "Ukraine.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "France",
                            Image = "France.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Greece",
                            Image = "Greece.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Portugal",
                            Image = "Portugal.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Netherlands",
                            Image = "Netherlands.png",
                            IsUsed = false
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Switzerland",
                            Image = "Switzerland.png",
                            IsUsed = false
                        });
                });

            modelBuilder.Entity("AgileCourseAssignment.Shared.Models.HighScoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HighScore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player1",
                            Score = 250,
                            Time = 120
                        },
                        new
                        {
                            Id = 2,
                            Name = "Player2",
                            Score = 180,
                            Time = 90
                        },
                        new
                        {
                            Id = 3,
                            Name = "Player3",
                            Score = 320,
                            Time = 150
                        },
                        new
                        {
                            Id = 4,
                            Name = "Player4",
                            Score = 200,
                            Time = 110
                        },
                        new
                        {
                            Id = 5,
                            Name = "Player5",
                            Score = 280,
                            Time = 130
                        });
                });

            modelBuilder.Entity("AgileCourseAssignment.Shared.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyInformation = "Im glad to announce that a project has started for fun learning experience.",
                            Titel = "Development"
                        },
                        new
                        {
                            Id = 2,
                            BodyInformation = "There is now a Quiz game where you guess the flag!",
                            Titel = "Quiz v.1"
                        },
                        new
                        {
                            Id = 3,
                            BodyInformation = "There is now a highscore page where you can compare results from yourself and others.",
                            Titel = "Highscore table"
                        },
                        new
                        {
                            Id = 4,
                            BodyInformation = "A second Quiz game has been added, check it out!",
                            Titel = "Quiz v.2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
